Repository omec-project/ngic-rtc, pull requests merged in 2019-03, with the labels that each got.

#37 Readme cleanup
  README.MD
Labels: cleanup, documentation

#64 Add .ci folder to host all customization
  .ci/tc1/cp/custom-cp.mk
  .ci/tc1/dp/custom-dp.mk
  .ci/tc2/cp/custom-cp.mk
  .ci/tc2/dp/custom-dp.mk
Labels: cleanup

#18 Move Makefile out of config folder
  cp/Makefile
  cp/custom-cp.mk
  dp/Makefile
  dp/custom-dp.mk
Labels: cleanup

#52 Dump the stack on catching SIGSEGV
  cp/main.c
  dp/main.c
  interface/interface.c
Labels: enhancement

#36 AVX patch for i40e dpdk-18.02 driver
  install.sh
  patches/avx_not_suported.patch
  patches/v2-net-i40e-fix-avx2-driver-check-for-rx-rearm.diff
Labels: cleanup

#35 Make all kni scripts path-aware.
  kni_ifcfg/kni-S1Udevcfg.sh
  kni_ifcfg/kni-S1Udevdel.sh
  kni_ifcfg/kni-SGIdevcfg.sh
  kni_ifcfg/kni-SGIdevdel.sh
Labels: cleanup

#27 Compile libgtpv2c as static library
  cp/Makefile
  libgtpv2c/Makefile
Labels: cleanup

#51 Add ability to resolve names in addition to IP
  cp/main.c
  dp/config.c
  interface/interface.c
  interface/interface.h
Labels: enhancement
